services:
  mongodb:
    image: mongo:7.0
    container_name: tw-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: tw_scrapper
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - tw-network

volumes:
  mongodb_data:

networks:
  tw-network:
    driver: bridge
