pipeline:
  name: "Job Link Extraction Pipeline"
  version: "1.0.0"
  description: "AI-powered job listing extraction and analysis from company career pages"

  # Directory structure and file paths
  paths:
    output_dir: "data"
    prompts_dir: "prompts"
    companies_file: "companies.yaml"

    # Output patterns for stages
    stage_output_patterns:
      output_dir: "pipeline_{stage_tag}"
      output_file: "{stage_tag}_results.json"

  # Integration configurations
  integrations:
    openai:
      model: "gpt-5-mini"
      max_retries: 3
      timeout: 30 # seconds

    # Playwright integration for web scraping
    web_extraction:
      browser_config:
        headless: true
        timeout: 30000 # milliseconds
        wait_until: domcontentloaded
      max_retries: 3
      retry_delay: 1.0 # seconds

  # Stages
  stages:
    stage_1:
      name: "Job Listing Extraction"
      tag: "stage_1"
      description: "Extract job titles and URLs from company career pages using web scraping and AI parsing"
      enabled: true
      openai_service:
        system_message: "You are an AI assistant specialized in extracting job listings from HTML content."
        prompt_template: "stage_1_jobs.md"
        prompt_variables:
          - html_content
          - company_name
        response_format:
          name: "JobListings"
          strict: true
          schema:
            type: "object"
            properties:
              jobs:
                type: "array"
                items:
                  type: "object"
                  properties:
                    title:
                      type: "string"
                      description: "Job title"
                    url:
                      type: "string"
                      description: "Full URL to job posting"
                  required: ["title", "url"]
                  additionalProperties: false
            required: ["jobs"]
            additionalProperties: false
    stage_2:
      name: "Job Eligibility and Metadata Extraction"
      tag: "stage_2"
      description: "Analyze job postings to determine eligibility, extract metadata, and generate concise descriptions"
      enabled: true
      openai_service:
        system_message: "You extract job descriptions, eligibility information, and basic metadata from HTML content."
        prompt_template: "stage_2_details.md"
        prompt_variables:
          - html_content
        response_format:
          name: "JobAnalysis"
          strict: true
          schema:
            type: "object"
            properties:
              job:
                type: "object"
                properties:
                  eligible:
                    type: "boolean"
                    description: "Whether the job meets eligibility criteria"
                  location:
                    type: "string"
                    enum: ["Costa Rica", "LATAM"]
                    description: "Job location"
                  work_mode:
                    type: "string"
                    enum: ["Remote", "Hybrid", "Onsite"]
                    description: "Work arrangement mode"
                  employment_type:
                    type: "string"
                    enum:
                      [
                        "Full-time",
                        "Part-time",
                        "Contract",
                        "Freelance",
                        "Temporary",
                        "Internship",
                      ]
                    description: "Type of employment"
                  experience_level:
                    type: "string"
                    enum:
                      [
                        "Entry-level",
                        "Junior",
                        "Mid-level",
                        "Senior",
                        "Lead",
                        "Principal",
                        "Executive",
                      ]
                    description: "Required experience level"
                  description:
                    type: "string"
                    maxLength: 500
                    description: "Concise job description focusing on role and responsibilities"
                required:
                  [
                    "eligible",
                    "location",
                    "work_mode",
                    "employment_type",
                    "experience_level",
                    "description",
                  ]
                additionalProperties: false
            required: ["job"]
            additionalProperties: false
