---
pipeline:
  name: "Job Link Extraction Pipeline"
  version: "1.0.0"
  description: >-
    AI-powered job listing extraction and analysis from company career pages

  # Directory structure and file paths
  paths:
    prompts_dir: "prompts"
    companies_file: "companies.yaml"

  # Integration configurations
  integrations:
    openai:
      model: "gpt-5-mini"
      max_retries: 3
      # timeout in seconds
      timeout: 600

    # Playwright integration for web scraping
    web_extraction:
      browser_config:
        headless: true
        # timeout in milliseconds
        timeout: 30000
        wait_until: domcontentloaded
      max_retries: 3
      # timeout in seconds
      retry_delay: 1.0

  # Stages
  stages:
    stage_1:
      name: "Job Listing Extraction"
      tag: "stage_1"
      description: >-
        Extract job titles and URLs from company career pages using web
        scraping and AI parsing
      enabled: true
      openai_service:
        system_message: >-
          You are an AI assistant specialized in extracting job listings
          from HTML content.
        prompt_template: "stage_1_jobs.md"
        prompt_variables:
          - html_content
          - company_name
        response_format:
          name: "JobListings"
          strict: true
          schema:
            type: "object"
            properties:
              jobs:
                type: "array"
                items:
                  type: "object"
                  properties:
                    title:
                      type: "string"
                      description: "Job title"
                    url:
                      type: "string"
                      description: "Full URL to job posting"
                  required: ["title", "url"]
                  additionalProperties: false
            required: ["jobs"]
            additionalProperties: false
    stage_2:
      name: "Job Eligibility and Metadata Extraction"
      tag: "stage_2"
      description: >-
        Analyze job postings to determine eligibility, extract metadata,
        and generate concise descriptions
      enabled: false
      openai_service:
        system_message: >-
          You extract job descriptions, eligibility information, and basic
          metadata from HTML content.
        prompt_template: "stage_2_details.md"
        prompt_variables:
          - html_content
        response_format:
          name: "JobAnalysis"
          strict: true
          schema:
            type: "object"
            properties:
              location:
                type: "string"
                enum: ["Costa Rica", "LATAM"]
                description: "Job location"
              work_mode:
                type: "string"
                enum: ["Remote", "Hybrid", "Onsite"]
                description: "Work arrangement mode"
              employment_type:
                type: "string"
                enum:
                  [
                    "Full-time",
                    "Part-time",
                    "Contract",
                    "Freelance",
                    "Temporary",
                    "Internship",
                  ]
                description: "Type of employment"
              experience_level:
                type: "string"
                enum:
                  [
                    "Entry-level",
                    "Junior",
                    "Mid-level",
                    "Senior",
                    "Lead",
                    "Principal",
                    "Executive",
                  ]
                description: "Required experience level"
              job_function:
                type: "string"
                enum:
                  [
                    "Technology & Engineering",
                    "Sales & Business Development",
                    "Marketing & Communications",
                    "Operations & Logistics",
                    "Finance & Accounting",
                    "Human Resources",
                    "Customer Success & Support",
                    "Product Management",
                    "Data & Analytics",
                    "Healthcare & Medical",
                    "Legal & Compliance",
                    "Design & Creative",
                    "Administrative & Office",
                    "Consulting & Strategy",
                    "General Management",
                    "Other",
                  ]
                description: "Job function category"
              province:
                type: "string"
                description: >-
                  Province name for Costa Rica locations or empty string for
                  LATAM
              city:
                type: "string"
                description: "City name or empty string"
              description:
                type: "string"
                maxLength: 500
                description: >-
                  Concise job description focusing on role and
                  responsibilities
            required:
              [
                "location",
                "work_mode",
                "employment_type",
                "experience_level",
                "job_function",
                "province",
                "city",
                "description",
              ]
            additionalProperties: false
    stage_3:
      name: "Job Skills and Responsibilities Extraction"
      tag: "stage_3"
      description: >-
        Extract detailed job information including responsibilities, required
        and preferred skills, and benefits from job posting HTML content
      enabled: false
      openai_service:
        system_message: >-
          You extract job skills and responsibilities from HTML content.
        prompt_template: "stage_3_skills.md"
        prompt_variables:
          - html_content
        response_format:
          name: "JobSkillsAndResponsibilities"
          strict: true
          schema:
            type: "object"
            properties:
              responsibilities:
                type: "array"
                items:
                  type: "string"
                description: >-
                  Action-oriented items describing what the person will do in
                  the role
              skill_must_have:
                type: "array"
                items:
                  type: "string"
                description: >-
                  Skills that are required, essential, or mandatory for the
                  role
              skill_nice_to_have:
                type: "array"
                items:
                  type: "string"
                description: >-
                  Skills that are preferred, bonus, or optional for the role
              benefits:
                type: "array"
                items:
                  type: "string"
                description: >-
                  Explicitly listed benefits, perks, and compensation details
            required:
              [
                "responsibilities",
                "skill_must_have",
                "skill_nice_to_have",
                "benefits",
              ]
            additionalProperties: false
    stage_4:
      name: "Technology Extraction and Categorization"
      tag: "stage_4"
      description: >-
        Extract and categorize technologies from job requirements, determining
        their requirement status and identifying main technologies for each role
      enabled: false
      openai_service:
        system_message: >-
          You extract and categorize technologies from structured job
          requirements.
        prompt_template: "stage_4_tech.md"
        prompt_variables:
          - requirements_json
        response_format:
          name: "TechnologyExtraction"
          strict: true
          schema:
            type: "object"
            properties:
              technologies:
                type: "array"
                items:
                  type: "object"
                  properties:
                    name:
                      type: "string"
                      description: "Canonical technology name"
                    category:
                      type: "string"
                      enum:
                        [
                          "programming",
                          "frontend",
                          "backend",
                          "databases",
                          "api",
                          "cloud",
                          "devops",
                          "observability",
                          "testing",
                          "os",
                          "ai",
                          "productivity",
                          "data",
                          "messaging",
                          "other",
                        ]
                      description: "Technology category"
                    required:
                      type: "boolean"
                      description: >-
                        Whether the technology is required (from must_have) or
                        optional (from nice_to_have)
                  required: ["name", "category", "required"]
                  additionalProperties: false
                description: >-
                  List of all technologies found in the job requirements
              main_technologies:
                type: "array"
                items:
                  type: "string"
                maxItems: 10
                description: >-
                  Up to 10 most essential technology names for the job,
                  prioritizing required technologies and core job functions
            required: ["technologies", "main_technologies"]
            additionalProperties: false
