pipeline:
  name: "Job Link Extraction Pipeline"
  version: "1.0.0"
  description: "AI-powered job listing extraction and analysis from company career pages"

  # Directory structure and file paths
  paths:
    output_dir: "data"
    prompts_dir: "prompts"
    companies_file: "companies.yaml"

    # Output patterns for stages
    stage_output_patterns:
      output_dir: "pipeline_{stage_tag}"
      output_file: "{stage_tag}_results.json"

  # Integration configurations
  integrations:
    openai:
      model: "gpt-5-mini"
      max_retries: 3
      timeout: 30 # seconds

    # Playwright integration for web scraping
    web_extraction:
      browser_config:
        headless: true
        timeout: 30000 # milliseconds
        wait_until: domcontentloaded
      max_retries: 3
      retry_delay: 1.0 # seconds

    loguru:
      level: "INFO"
      format_console: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"

  # Stages
  stages:
    stage_1:
      name: "Job Listing Extraction"
      tag: "stage_1"
      description: "Extract job titles and URLs from company career pages using web scraping and AI parsing"
      enabled: true
      openai_service:
        system_message: "You are an AI assistant specialized in extracting job listings from HTML content."
        prompt_template: "stage_1_jobs.md"
        prompt_variables:
          - html_content
          - company_name
        response_format:
          type: "json_object"
          schema:
            type: "object"
            properties:
              jobs:
                type: "array"
                items:
                  type: "object"
                  properties:
                    title:
                      type: "string"
                      description: "Job title"
                    url:
                      type: "string"
                      description: "Full URL to job posting"
                    signature:
                      type: "string"
                      description: "SHA256 hash signature for duplicate detection"
                  required: ["title", "url", "signature"]
