pipeline:
  name: "Job Link Extraction Pipeline"
  version: "1.0.0"
  description: "AI-powered job listing extraction and analysis from company career pages"

  # Global defaults that stages can override
  defaults:
    openai:
      model: "gpt-4o-mini"
      temperature: 0.1
      max_tokens: 4000
      timeout: 30
      max_retries: 3

    retry_policy:
      max_retries: 3
      retry_delay: 1.0
      backoff_multiplier: 2.0
      retry_on_failure: true

    file_handling:
      encoding: "utf-8"
      backup_enabled: true
      compression: false
      save_output: true

    browser:
      headless: true
      timeout: 30000
      wait_until: "domcontentloaded"
      user_agent: ""

  # Directory structure and file paths
  paths:
    input_dir: "input"
    output_dir: "data"
    prompts_dir: "input/prompts"
    companies_file: "input/companies.yaml"
    logs_dir: "logs"
    config_dir: "config"

  output_structure:
    timestamp_format: "%Y%m%d"
    stage_dir_pattern: "pipeline_stage_{stage}"
    backup_dir: "backups"
    file_patterns:
      stage_output: "jobs_stage_{stage}.json"
      combined_output: "all_jobs_stage_{stage}.json"
      historical: "historical_jobs_{date}.json"

  # Global validation and processing rules
  validation:
    required_company_fields: ["name", "career_url", "enabled", "web_parser"]
    required_web_parser_fields: ["type", "selectors"]
    job_signature_algorithm: "sha256"
    duplicate_detection: true

  processing:
    concurrent_limit: 5
    rate_limiting:
      requests_per_minute: 60
      delay_between_companies: 1.0

    filtering:
      skip_disabled_companies: true
      skip_duplicate_jobs: true
      min_job_title_length: 3

  # Integration configurations
  integrations:
    prefect:
      flow_timeout: 3600
      task_timeout: 300
      log_level: "INFO"
      default_retries: 2
      retry_delay: 30

    playwright:
      browser_type: "chromium"
      wait_strategies: ["domcontentloaded", "networkidle"]
      navigation_timeout: 30000

    openai:
      request_timeout: 30
      max_concurrent_requests: 10
      rate_limit_buffer: 0.1

  # Logging configuration
  logging:
    level: "INFO"
    format: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
    rotation: "1 day"
    retention: "7 days"
    compression: "gz"
