pipeline:
  name: "Job Link Extraction Pipeline"
  version: "1.0.0"
  description: "AI-powered job listing extraction and analysis from company career pages"

  # Directory structure and file paths
  paths:
    output_dir: "data"
    config_dir: "config"
    prompts_dir: "prompts"
    companies_file: "config/companies.yaml"

  output_structure:
    timestamp_format: "%Y%m%d"
    stage_dir_pattern: "pipeline_stage_{stage}"
    file_patterns:
      stage_output: "jobs_stage_{stage}.json"

  # Max number of tasks (companies) per stage in the pipeline
  processing:
    max_concurrent: 3

  # Integration configurations
  integrations:
    prefect:
      flow_timeout: 3600
      task_timeout: 300
      log_level: "INFO"
      default_retries: 2
      retry_delay: 30

    playwright_browser:
      headless: true
      timeout: 30000
      wait_until: "domcontentloaded"
      user_agent: ""

    openai:
      model: "gpt-5-mini"
      timeout: 30
      max_retries: 3
      request_timeout: 30

  # Logging configuration
  logging:
    level: "INFO"
    format_console: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level: <8}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
    format_file: "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
    rotation: "10 MB"
    retention: "7 days"
