stages:
  stage_1:
    name: "Job Listing Extraction"
    description: "Extract job titles and URLs from company career pages using web scraping and AI parsing"
    enabled: true

    # Stage-specific OpenAI configuration
    openai_service:
      system_message: "You are an AI assistant specialized in extracting job listings from HTML content."
      response_format:
        type: "json_object"
        schema:
          type: "object"
          properties:
            jobs:
              type: "array"
              items:
                type: "object"
                properties:
                  title:
                    type: "string"
                    description: "Job title"
                  url:
                    type: "string"
                    description: "Full URL to job posting"
                  signature:
                    type: "string"
                    description: "SHA256 hash signature for duplicate detection"
                required: ["title", "url", "signature"]

    # Input/Output configuration
    input:
      prompt_template: "stage_1_jobs.md"
